spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/junit_db
    username: dev_user
    password: dev_user
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true